help:
	@echo "The following make targets are available:\n"
	@echo "   build        build python package"
	@echo "   clean        clean up package and cruft"
.PHONEY: help

build: 
	python3 -m build
.PHONEY: build

clean:
	rm -rf dist
	rm -rf ET44fwupdater.egg-info
	rm -rf 
.PHONEY: clean
